language: generic
addons:
    apt:
        sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
os:
- osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            # safelist
branches:
  only:
  - master
  - stable
script:
- mkdir build
- cd build
- cmake .. && make
