language: generic

matrix:
  include:
  - os: linux
          compiler: clang
          env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
          addons:
            apt:
                packages:
                    - clang-3.7
                sources: *sources
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            # safelist
branches:
  only:
  - master
  - stable
script:
- mkdir build
- cd build
- cmake .. && make
